# Generated by Django 3.0.4 on 2020-05-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.ManyToManyField(null=True, related_name='topics', to='web.Topic'),
        ),
    ]
