# Generated by Django 3.0.4 on 2020-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200503_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='topic',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic',
            field=models.ManyToManyField(null=True, related_name='topics', to='web.Article'),
        ),
    ]
