# Generated by Django 3.0.4 on 2020-05-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200503_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='articles',
        ),
    ]
