# Generated by Django 3.0.4 on 2020-05-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200503_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ManyToManyField(to='web.Topic'),
        ),
    ]
