apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: elk
  name: elk
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elk
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: elk
    spec:
      containers:
      - image: sebp/elk
        imagePullPolicy: ""
        name: elk
        ports:
        - containerPort: 5601
        - containerPort: 9200
        - containerPort: 5044
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
