apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: graphana
  name: graphana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: graphana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: graphana
    spec:
      containers:
      - env:
        - name: GF_INSTALL_PLUGINS
          value: grafana-clock-panel,grafana-simple-json-datasource
        - name: GF_PATHS_CONFIG
          value: /usr/local/etc/grafana/grafana.ini
        image: graphana
        imagePullPolicy: ""
        name: graphana
        ports:
        - containerPort: 3031
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: graphana-claim0
        - mountPath: /var/log/grafana/grafana.log
          name: graphana-claim1
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: graphana-claim0
        persistentVolumeClaim:
          claimName: graphana-claim0
      - name: graphana-claim1
        persistentVolumeClaim:
          claimName: graphana-claim1
status: {}
